version: 2
jobs:
  build:
    docker:
      - image: 'fpco/stack-build:lts'
    steps:
      - checkout
      - restore_cache:
          key: 'v3-indents-{{ arch }}-{{ .Branch }}'
      - run:
          name: 'Test'
          command: 'stack test --no-terminal'
      - save_cache:
          key: 'v3-indents-{{ arch }}-{{ .Branch }}-{{ .Revision }}'
          paths:
            - '~/.stack-work'
            - '~/.stack'
